# Rewrites backend/contracts/.env and backend/keeper/.env for Robinhood Chain
# mainnet (chain 4663), carrying the existing secrets across untouched.
#
# Nothing in this file is a secret: the keys are read out of the .env files
# already on disk and written straight back, never typed and never printed.
# The old files are copied to .env.bak first.
#
# Run from anywhere:
#   powershell -ExecutionPolicy Bypass -File D:\dev\fxperps\backend\setup-env.ps1

$ErrorActionPreference = "Stop"

$backend   = Split-Path -Parent $MyInvocation.MyCommand.Path
$contracts = Join-Path $backend "contracts\.env"
$keeper    = Join-Path $backend "keeper\.env"

# A .env value, or "" when the file or the key is absent. Split on the FIRST
# "=" only: a base64 API key can contain one.
function Get-EnvValue([string]$Path, [string]$Name) {
    if (-not (Test-Path $Path)) { return "" }
    $line = Get-Content $Path | Where-Object { $_ -match "^$Name=" } | Select-Object -First 1
    if (-not $line) { return "" }
    return ($line -split "=", 2)[1].Trim()
}

# UTF-8 with no BOM. With one, three invisible bytes land in front of the first
# variable name and the parser never sees it.
function Write-EnvFile([string]$Path, [string]$Content) {
    $dir = Split-Path -Parent $Path
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    if (Test-Path $Path) { Copy-Item $Path "$Path.bak" -Force }
    [System.IO.File]::WriteAllText($Path, $Content, (New-Object System.Text.UTF8Encoding $false))
}

$deployerKey  = Get-EnvValue $contracts "DEPLOYER_KEY"
$explorerKey  = Get-EnvValue $contracts "EXPLORER_API_KEY"
$keeperKey    = Get-EnvValue $keeper    "KEEPER_KEY"
$pythApiKey   = Get-EnvValue $keeper    "PYTH_API_KEY"

# A keeper with no key of its own is the deployer signing maintenance calls.
# That is the arrangement in place; carrying it across is not endorsing it.
if (-not $keeperKey) { $keeperKey = $deployerKey }

$contractsEnv = @"
# Robinhood Chain mainnet, chain 4663. Never commit this file.
# Generated by backend/setup-env.ps1 - the previous file is at .env.bak

# --- chain: Arbitrum Sepolia (kept so --rpc-url arbitrum_sepolia resolves) ---
TESTNET_RPC_URL=https://sepolia-rollup.arbitrum.io/rpc
TESTNET_CHAIN_ID=421614

# --- chain: Robinhood Chain (the live target) --------------------------------
RPC_URL=https://rpc.mainnet.chain.robinhood.com
CHAIN_ID=4663

# --- deployer ----------------------------------------------------------------
DEPLOYER_KEY=$deployerKey

# --- settlement --------------------------------------------------------------
# USDG, Robinhood Chain's native stablecoin, read off the chain rather than
# copied: symbol() answers "USDG", decimals() answers 6, totalSupply() answers
# ~719.8M. Blank on chain 4663 and Deploy.s.sol refuses to run, because the
# fallback there is a mock token with an open mint.
USDG_ADDRESS=0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168

# --- oracle ------------------------------------------------------------------
# BLANK ON PURPOSE. The address that used to sit here is Pyth on Arbitrum
# Sepolia; on chain 4663 that address holds no code at all, and a PythOracle
# pointed at it would deploy cleanly and fail on the first trade. Deploy puts
# up a MockOracle, SetPushOracle then replaces it with the PushOracle the
# keeper publishes to.
PYTH_ADDRESS=
# Seconds a mark may be old before its market stops trading.
ORACLE_MAX_AGE=300
# Widest publisher confidence interval tolerated, in bps. PythOracle only.
ORACLE_MAX_CONFIDENCE_BPS=50
# Largest single move a publisher may post, in bps. PushOracle only.
ORACLE_MAX_DEVIATION_BPS=500

# --- push oracle publisher ---------------------------------------------------
# The address SetPushOracle authorises to post marks.
KEEPER_ADDRESS=0x354Bfdce4877fEC2fa5b5eE1619aba2F3E6076eE

# --- liquidity ---------------------------------------------------------------
# Whole USDG for ProvideLiquidity.s.sol. Real tokens, not minted - they leave
# the provider's balance. This number is the venue's open-interest ceiling.
POOL_LIQUIDITY=

# --- explorer ----------------------------------------------------------------
EXPLORER_API_URL=https://robinhoodchain.blockscout.com/api
EXPLORER_API_KEY=$explorerKey
"@

$keeperEnv = @"
# Robinhood Chain mainnet, chain 4663. Never commit this file.
# Generated by backend/setup-env.ps1 - the previous file is at .env.bak
#
# This key signs nothing but maintenance calls: posting marks and liquidating
# positions. Neither can move anyone's balance.

# --- chain -------------------------------------------------------------------
RPC_URL=https://rpc.mainnet.chain.robinhood.com
CHAIN_ID=4663
KEEPER_KEY=$keeperKey

# --- oracle kind ---------------------------------------------------------------
# push: fetch conventional FX rates and post them to the PushOracle, where this
# keeper is the named publisher and decides the mark.
ORACLE_KIND=push
FX_URL=https://api.fxratesapi.com/latest
# How far a rate must move before it is worth a transaction, in bps. A pair
# that has not moved keeps its mark; one ageing past half the staleness window
# is refreshed regardless.
MIN_MOVE_BPS=2

# --- contracts ---------------------------------------------------------------
# FILL AFTER THE MAINNET DEPLOY, from deployments/4663.json. The values that
# were here belong to Arbitrum Sepolia and address nothing on chain 4663.
ENGINE_ADDRESS=
ORACLE_ADDRESS=
# Pyth's own contract. Blank: this deployment does not use Pyth.
PYTH_ADDRESS=

# --- cadence, in seconds -----------------------------------------------------
PRICE_INTERVAL=15
LIQUIDATION_INTERVAL=20
SNAPSHOT_INTERVAL=1200
# The deploy block on THIS chain. Robinhood Chain prunes state to roughly the
# last 6000 blocks, so scanning from 0 is both slow and pointless.
START_BLOCK=

# --- pyth --------------------------------------------------------------------
# Unused while ORACLE_KIND=push. Kept so switching back needs no archaeology.
HERMES_URL=https://pyth.dourolabs.app/hermes
PYTH_API_KEY=$pythApiKey
"@

Write-EnvFile $contracts $contractsEnv
Write-EnvFile $keeper    $keeperEnv

# Report by length, never by value.
function Show-Secret([string]$Path, [string]$Name) {
    $value = Get-EnvValue $Path $Name
    $state = if ($value) { "$($value.Length) chars" } else { "EMPTY" }
    Write-Host ("  {0,-18} {1}" -f $Name, $state)
}

Write-Host ""
Write-Host "contracts/.env written (backup at .env.bak)"
Show-Secret $contracts "DEPLOYER_KEY"
Show-Secret $contracts "EXPLORER_API_KEY"
Get-Content $contracts | Select-String "^(RPC_URL|CHAIN_ID|USDG_ADDRESS|PYTH_ADDRESS|KEEPER_ADDRESS|POOL_LIQUIDITY)=" | ForEach-Object { Write-Host "  $_" }

Write-Host ""
Write-Host "keeper/.env written (backup at .env.bak)"
Show-Secret $keeper "KEEPER_KEY"
Show-Secret $keeper "PYTH_API_KEY"
Get-Content $keeper | Select-String "^(RPC_URL|CHAIN_ID|ORACLE_KIND|ENGINE_ADDRESS|ORACLE_ADDRESS|START_BLOCK)=" | ForEach-Object { Write-Host "  $_" }

Write-Host ""
Write-Host "Next: set POOL_LIQUIDITY, then deploy. ENGINE_ADDRESS, ORACLE_ADDRESS"
Write-Host "and START_BLOCK in keeper/.env are filled from deployments/4663.json"
Write-Host "after the deploy, not before."
